### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by hdacnw** [thinksquirrel/fluviofx#19] opened 2019-06-20 20:05 UTC
Compilation fails with the following error message (in console).
```
ArgumentNullException: Value cannot be null.
Parameter name: type
Thinksquirrel.FluvioFX.Editor.ReflectionHelpers.Invoke[T] (System.Type type, System.String methodName, Thinksquirrel.FluvioFX.Editor.Parameter[] parameters) (at Library/PackageCache/com.thinksquirrel.fluviofx@99cca250b4e55486e22785c8eb0e522bf0151734/ReflectionHelpers/ReflectionHelpers.cs:275)
Thinksquirrel.FluvioFX.Editor.FluvioFXInstall.GetPackagePath (System.String pkgName) (at Library/PackageCache/com.thinksquirrel.fluviofx@99cca250b4e55486e22785c8eb0e522bf0151734/Install/FluvioFXInstall.cs:262)
Thinksquirrel.FluvioFX.Editor.FluvioFXInstall.Install (System.Boolean force) (at Library/PackageCache/com.thinksquirrel.fluviofx@99cca250b4e55486e22785c8eb0e522bf0151734/Install/FluvioFXInstall.cs:126)
Thinksquirrel.FluvioFX.Editor.FluvioFXInstall.UpdateEvt () (at Library/PackageCache/com.thinksquirrel.fluviofx@99cca250b4e55486e22785c8eb0e522bf0151734/Install/FluvioFXInstall.cs:113)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)
```
Tried reimporting and reinstalling but the error persists. 

* Unity version 2019.3.0a5 on Windows 10
* HDRP version 6.7.1
* VFX graph version 6.7.1
* Graphic device: GeForce GTX950M

Thank you.

**Comment by lmontoute** [comment] 2019-06-22 00:48
I can't support alphas right now but this seems to happen in .2 as well. Thanks for the report!

**Comment by lmontoute** [comment] 2019-06-22 00:49
Duplicate of #20

**Closed by lmontoute** 2019-06-22 00:49 UTC
Labels: duplicate
