### ISSUE TITLE
Package manager startup errors on 2019.1.8f1 on Windows 10

### ISSUE THREAD

**Issue by gpoole** [thinksquirrel/fluviofx#22] opened 2019-07-03 06:04 UTC
When I'm opening a project in 2019.1.8f1 with FluvioFX installed I'm often getting `EPERM: operation not permitted` errors related to `VFXCodeGenerator.cs`. If I select quit and reopen Unity a few times it'll eventually work.

![Capture2](https://user-images.githubusercontent.com/2898433/60556425-93a7c380-9d84-11e9-9605-3adc9140c1b3.PNG)

**Comment by lmontoute** [comment] 2019-07-06 00:10
Hi @gpoole,

Can you give the latest PR a try and see if that fixes your issue? Note the change with installation instructions as well. You may need to remove and reinstall the needed packages in order to get things working.

**Comment by lmontoute** [comment] 2019-07-06 00:11
I can't reproduce this one, but it _may_ be fixed with #23.

**Comment by gpoole** [comment] 2019-07-06 07:28
I also didn't have this problem when I tried installing on my Mac, so could it be a Windows-specific problem? I know Windows is a lot more strict with locking files and preventing writes to files while they're being read by other processes, could it be something to do with that?

**Comment by lmontoute** [comment] 2019-07-06 19:21
This might be specific to your system. Can you provide more details?

- Windows version
- Do you have anything unique about your project folder structure (is it under a symlink or on a different drive, etc)
- Does this happen with a completely empty (new) project?

**Comment by gpoole** [comment] 2019-07-08 02:32
I'm running Windows 10 (1803). There isn't anything unusual I can think of about the setup, no symlinks or drive differences or anything odd. I was able to reproduce it with a new project just now, here's the manifest.json: https://gist.github.com/gpoole/691e900dc4a2b954b1c4c3cc47ea062c If it helps I can also push the whole project up as a repo?

I had more of a poke around and found:
* If I disable the Fluvio auto installer by removing `[InitializeOnLoad]` and don't manually run it then ut restarts fine
* If I manually modify the files the installer is changing by adding a comment to them, vscode tells me the file is read only and removes the read only flag when I save, but I still don't get any errors on restart
* If I then manually run the installer from the menu I get the error after a restart

I wondered if it might be something to do with the readonly flag, so tried commenting out just the code in the installer that restores the readonly flag after modifying the files (e.g. I commented https://github.com/thinksquirrel/fluviofx/blob/master/Install/FluvioFXInstall.cs#L338) and it seems to be fine restarting after that.

**Comment by lmontoute** [comment] 2019-07-15 19:38
Hm, this is likely the case. It could be that marking that as read-only again causes problems on some systems.

I don't think there is any problem with keeping the file writable, to be honest. So I'll just remove that line.

Thanks for troubleshooting this!

**Comment by lmontoute** [comment] 2019-07-15 19:41
I've just made and pushed this update. Can you confirm that the PR works as-is? If so I'll go ahead and merge.

**Comment by gpoole** [comment] 2019-07-16 00:01
Great, thanks for the fix, yep it's not showing the error anymore when I restart. Very strange, it doesn't seem like setting and unsetting the flag should have mattered.

**Comment by lmontoute** [comment] 2019-07-16 21:55
Fixed by #23

**Closed by lmontoute** 2019-07-16 21:55 UTC
